main: com.geppi.main.Main
version: 1.0
api-version: 1.16
name: Core

commands:
  Killstreak:
  Ks:
  Money:
  Bal:
  Balance:
  Setwarp:
  Warn:
  Worldtp:
  Worlds:
  Warp:
  Delwarp:
  Warplist:
  Feed:
  Kit:
  Economy:
  SetRank:
  Rankup:
  Jail:
  Speedreset:
  Gamemode:
  Gm:
  Reply:
  Nickname:
  Nick:
  Unjail:
  Token:
  Tokeneco:
  Tokeneconomy:
  DonateAdmin:
  Vanish:
  Home:
  V:
  Hat:
  Help:
  Playerhead:
  Tokenshop:
  Tshop:
  PVP:
  R:
  PV:
  Playervault:
  Speed:
  Sethome:
  Clearlag:
  Delhome:
  Homelist:
  Bail:
  Namecolor:
  Donationadmin:
  Unmute:
  Spawn:
  Unban:
  Buy:
  Eco:
  Rename:
  Kits:
  Clearchat:
  Suicide:
  Donations:
  Donate:
  SetupMap:
  Refer:
  Refers:
  Vote:
  Trails:
  Voteadmin:
  Mute:
  Ban:
  List:
  Contraban:
  Trailremove:
  Stats:



